version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

brews:
  - directory: Formula
    repository:
      owner: jeryldev
      name: homebrew-tap
    homepage: "https://github.com/jeryldev/kb"
    description: "Terminal Kanban board for personal project management"
    license: "MIT"
    install: |
      bin.install "kb"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
